---

- name: Install requirements (Debian)
  apt:
    name:
      - postfix
      - ca-certificates
      - mailutils
      - libsasl2-modules
    update_cache: yes

- name: Install DKIM requirements (Debian)
  apt:
    name:
      - opendkim
      - opendkim-tools
  when: postfix_dkim

- name: Install postfix-pcre
  apt: pkg=postfix-pcre
  when: postfix_rewrite_sender_address | length > 0 or postfix_local_user_relay_address | length > 0
